---
name: DBIx-Custom-Query
version: 0.0101
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
abstract: Query object for DBIx::Custom
license: perl
resources:
  license: ~
requires:
  Object::Simple: 2.0702
build_requires:
  Test::More: 0
provides:
  DBIx::Custom::Query:
    file: lib/DBIx/Custom/Query.pm
    version: 0.0101
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
